import Image from "next/image";
import Link from "next/link";
import { Compass, Layers3, Code2, ChartNoAxesCombined } from "lucide-react";
import type { SiteContent } from "@/lib/content-schema";
import { BrandWatermark } from "@/components/brand";
import { Label, TextLink, ProjectCard, ProcessGrid, Closing } from "@/components/ui";
const icons = [Compass, Layers3, Code2, ChartNoAxesCombined];
export function HomeView({ c }: { c: SiteContent }) {
  return <>
    <section className="hero"><Image src={c.hero.image} alt={c.hero.imageAlt} fill preload sizes="(max-width: 800px) 180vh, 100vw" className="hero-image" /><div className="hero-shade" /><div className="hero-content container"><Label><span className="hero-reveal">{c.hero.eyebrow}</span></Label><h1 className="hero-reveal"><span className="hero-heading-lead">{c.hero.heading}</span><em>{c.hero.highlight}</em></h1><p className="hero-description hero-reveal">{c.hero.description}</p><div className="hero-actions hero-reveal"><Link href="/contact" className="button button-gold">{c.hero.primaryCta}</Link><Link href="/work" className="hero-secondary">{c.hero.secondaryCta}</Link></div></div><div className="hero-bottom container hero-reveal"><a href="#philosophy" className="scroll-cue"><span className="scroll-line" />SCROLL TO EXPLORE</a><p>YOUR VISION.<br />OUR DIRECTION.</p></div></section>
    <section id="philosophy" className="intro-section container"><div className="intro-grid" data-reveal><div><Label>{c.intro.eyebrow}</Label><h2>{c.intro.heading}</h2></div><div className="intro-copy"><p>{c.intro.description}</p><p>{c.intro.detail}</p><TextLink href="/about">Meet the studio</TextLink></div></div><div className="intro-signoff"><span>STRATEGY. DESIGN. TECHNOLOGY. GROWTH.</span><span>ONE CONNECTED VISION.</span></div></section>
    <section className="capabilities-section"><div className="container"><div className="section-heading" data-reveal><div><Label>OUR CAPABILITIES</Label><h2>{c.capabilities.heading}</h2></div><TextLink href="/services">Explore our services</TextLink></div><div className="capabilities-grid">{c.capabilities.items.map((item, i) => { const Icon = icons[i % 4]; return <Link key={i} href={`/services/${item.slug}`} className="capability" data-reveal><div className="capability-top"><span>0{i + 1}</span><Icon size={29} strokeWidth={1} aria-hidden="true" /></div><h3>{item.title}</h3><p>{item.description}</p><span className="capability-tags">{item.tags}</span><span className="capability-link">Explore <span>+</span></span></Link>; })}</div></div></section>
    <section className="work-section container"><div className="section-heading" data-reveal><div><Label>SELECTED WORK</Label><h2>{c.work.heading}</h2></div><TextLink href="/work">View all work</TextLink></div><div className="projects-grid">{c.projects.slice(0, 2).map((p, i) => <ProjectCard key={p.slug} project={p} index={i} />)}</div></section>
    <section className="thinking-section container"><div className="section-heading" data-reveal><div><Label>BEHIND THE EXPERIENCE</Label><h2>{c.thinking.heading}</h2></div><p className="heading-aside">{c.thinking.description}</p></div><div className="thinking-grid">{c.thinking.items.map((item, i) => <article key={i} data-reveal><span className="eyebrow">0{i + 1} / THE MECHANISM</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></section>
    <section className="process-section"><div className="container"><div className="section-heading" data-reveal><div><Label>OUR APPROACH</Label><h2>{c.process.heading}</h2></div><div className="heading-aside"><p>{c.process.description}</p><TextLink href="/process">Our process</TextLink></div></div><ProcessGrid content={c.process} /></div></section>
    <section className="industries-section container"><div data-reveal><Label>UNDERSTANDING YOUR WORLD</Label><h2>{c.industries.heading}</h2><p>{c.industries.description}</p></div><div className="industry-list" data-reveal>{c.industries.items.map((item, i) => <Link href="/contact" key={i}><span>0{i + 1}</span><h3>{item}</h3><span className="industry-plus">+</span></Link>)}</div></section>
    <section className="partnership-section"><BrandWatermark /><div className="container" data-reveal><Label>MORE THAN A PROJECT. A PARTNERSHIP.</Label><h2>{c.partnership.heading}</h2><p>{c.partnership.description}</p><TextLink href="/contact" light>Let’s find your direction</TextLink></div></section>
    <Closing content={c} />
  </>;
}
