import { getContent } from "@/lib/content";
import { pageMetadata } from "@/lib/metadata";
import { PageHero } from "@/components/ui";
export const metadata = pageMetadata("Privacy Policy", "How VisionHelm handles information submitted through this website.", "/privacy");
export default async function Privacy() {
  const c = await getContent(); const legal = c.legal;
  const email = legal.privacyContact || c.brand.email;
  return <><PageHero label="THE DETAILS" title="Privacy, considered." /><article className="legal-content container">{(!legal.entity || !legal.effectiveDate || !email) && <p className="legal-draft">Draft policy. Business identity, contact details, and an effective date must be confirmed before this website launches publicly.</p>}{legal.effectiveDate && <p>Effective date: {legal.effectiveDate}</p>}<h2>Who we are</h2><p>{legal.entity || "VisionHelm (legal business details pending confirmation)"} operates this website.</p><h2>Information you choose to share</h2><p>When you submit a project inquiry, we receive the name, email address, company, services of interest, and project details you provide. Website, budget, and timeframe details are optional. Please do not include sensitive personal information in your inquiry.</p><h2>How we use your information</h2><p>We use inquiry information to respond to your request, understand your project, and discuss a potential engagement. We do not sell your personal information.</p><h2>Service providers</h2><p>Hosting providers process technical request data to serve this website. When configured, Resend processes inquiry emails for delivery. Information may be processed outside your country, depending on the provider and hosting configuration.</p><h2>Cookies and storage</h2><p>The public website does not set advertising cookies. The content editor uses a necessary, secure session cookie for authentication. Temporary preview drafts remain in memory and are not saved unless the editor chooses to save them.</p><h2>Retention and your choices</h2><p>Inquiry information should be retained only as long as necessary to respond to the inquiry, manage an engagement, or meet applicable legal obligations. You may request access, correction, or deletion of your information, subject to applicable law.</p><h2>Contact</h2>{email ? <p>For privacy questions, contact <a href={`mailto:${email}`}>{email}</a>.</p> : <p>Privacy contact details are awaiting configuration. Do not submit personal information until these details are confirmed.</p>}{legal.privacyAdditional && <p style={{ whiteSpace: "pre-wrap" }}>{legal.privacyAdditional}</p>}</article></>;
}
